package axel.jlambda;

public enum function_name {
	EXP,
	SIN,COS,TAN,CSC,SEC,COT,
	SINH,COSH,TANH,CSCH,SECH,COTH,
	LN,LOG,
	RE,IM,
	FLOOR,CEIL,ROUND,
	ABS,SQRT,ROOT,INV,
	ASIN,ACOS,ATAN,ACSC,ASEC,ACOT,
	ASINH,ACOSH,ATANH,ACSCH,ASECH,ACOTH,
	GAMMA
}
